<#
.SYNOPSIS
    This script searches for PowerShell scripts within a specified root folder and its subdirectories, and identifies those that are missing corresponding permissions JSON files.

.PARAMETER includedScope
    An array of strings specifying the directory names to include in the search. Default is @("device", "group", "org", "user").

.PARAMETER rootFolder
    The root folder path to start the search. Default is the current location.

.PARAMETER outputPath
    The file path where the list of scripts missing permissions JSON files will be saved.
    If not specified, the list will not be saved to a file and will only be displayed in the console.

.DESCRIPTION
    This script recursively searches through the specified root folder for PowerShell scripts (*.ps1) and checks if they have corresponding permissions JSON files either in the same folder or in a ".permissions" subfolder. If a script is missing its permissions JSON file, its path is added to a list. The list is then saved to the specified output file.

.NOTES
    - The script excludes itself from the search results.
    - The output file is created if it does not exist.
#>
param(
    [string[]]$includedScope = @("device", "group", "org", "user"),
    [string]$rootFolder = (Get-Location).Path,
    [string]$outputPath
)

$missingPermissions = ""
$existingPermissions = ""
$runbookCounter = 0
$missingPermissionsCounter = 0

# Prepare the markdown content variable
$markdownContent = ""
$markdownContent += "# Missing permissions JSON files`n`n"
$markdownContent += "## Overview`n`n"
$markdownContent += "This document lists all the runbooks that are missing permissions JSON files. The list is generated by searching for PowerShell scripts in the specified root folder and its subdirectories, and checking for corresponding permissions JSON files.`n`n"


Get-ChildItem -Path $rootFolder -Recurse -Include "*.ps1" -Exclude $MyInvocation.MyCommand.Name | Where-Object {
    $includedScope -contains $_.Directory.Parent.Name
} | ForEach-Object {
    $CurrentObject = $_
    $runbookCounter ++
    $relativeRunbookPath = $CurrentObject.FullName -replace "^$rootFolder[\\/]*", ""
    $RelativeRunbookPath_PathOnly = Split-Path -Path $relativeRunbookPath

    $permissionsPath_separateFolder = Join-Path -Path $rootFolder -ChildPath ".permissions\$RelativeRunbookPath_PathOnly\$($CurrentObject.BaseName).json"
    $permissionsPath_sameFolder = $($CurrentObject.FullName) -replace ".ps1", ".permissions.json"

    # Check if the permissions file exists in the same folder as the runbook or in the .permissions folder
    if (-not (Test-Path -Path $permissionsPath_sameFolder) -and -not (Test-Path -Path $permissionsPath_separateFolder)) {
        $missingPermissions += " - $($RelativeRunbookPath_PathOnly)/$($CurrentObject.BaseName)`n"
        $missingPermissionsCounter ++
    }
    else {
        $existingPermissions += " - $($RelativeRunbookPath_PathOnly)/$($CurrentObject.BaseName)`n`n"
    }
}

Write-Output "Total runbooks: $runbookCounter"
if ($missingPermissionsCounter -gt 0) {
    Write-Output "Runbooks with permissions: $($runbookCounter - $missingPermissionsCounter)"
    Write-Output "Runbooks missing permissions: $missingPermissionsCounter"
    Write-Output ""
    Write-Output "Currently missing permissions:"
    Write-Output $missingPermissions
}
else {
    Write-Output "No runbooks missing permissions."
}

if ($outputPath) {
    if ($missingPermissionsCounter -gt 0) {
        Write-Output "Missing permissions found. Saving to $outputPath"

        # Generate the markdown content for the missing permissions
        $markdownContent += "Total runbooks: $($runbookCounter)`n`n"
        $markdownContent += "Runbooks with permissions: $($runbookCounter - $missingPermissionsCounter)`n`n"
        $markdownContent += "Runbooks missing permissions: $($missingPermissionsCounter)`n`n"
        $markdownContent += "## List of files`n`n"
        $markdownContent += "Runbooks, which currently have missing permission files:`n`n"
        $markdownContent += $missingPermissions

        # Validate if the output path is a file
        if (-not (Test-Path -Path $outputPath)) {
            New-Item -Path $outputPath -ItemType File -Force | Out-Null
        }
        # Save the list of runbooks missing permissions to the output file
        Out-File -FilePath $outputPath -InputObject $markdownContent -Encoding utf8 -Force
    }
    else {
        Write-Output "No missing permissions found."

        # Check if there is missing permission report, if so remove it
        if (Test-Path -Path $outputPath) {
            Remove-Item -Path $outputPath -Force
            Write-Output "Removed the missing permission report, as there are no missing permissions."
        }
    }
}